apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    application: ${APPLICATION_NAME}
  name: ${APPLICATION_NAME}-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLUME_CAPACITY}