---
apiVersion: "v1"
kind: "Template"
metadata:
  name: "tibco-ems"
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: true
  value: tibcoems
- description: Size of the data and log volume
  name: VOLUME_CAPACITY
  required: true
  value: 512Mi
- description: The name of the secret containing the certificate files
  name: EMS_SECRET_NAME
  required: true
  value: ems-secrets